name: feature_community
description: feature community package.
publish_to: none

environment:
  sdk: 3.2.6
  flutter: 3.16.9

dependencies:
  flutter:
    sdk: flutter

  community_data:
    path: ../../data
  community_domain:
    path: ../../domain
  community_presentation:
    path: ../../presentation

  community_di:
    path: ../../di

  core_flutter_bloc:
    path: ../../../../core/flutter_bloc
  core_util:
    path: ../../../../core/util

  tool_clind_component:
    path: ../../../../tool/clind/component
  tool_clind_theme:
    path: ../../../../tool/clind/theme