name: clind_server_real
description: A server app using the shelf package and Docker.
version: 1.0.0

environment:
  sdk: 3.2.6

dependencies:
  args: 2.5.0
  faker: 2.1.0
  json_annotation: 4.9.0
  shelf: 1.4.1
  shelf_router: 1.1.4
  shelf_swagger_ui: 1.0.0+2

dev_dependencies:
  build_runner: 2.4.9
  http: 1.2.0
  json_serializable: 6.8.0