name: community_domain
description: feature community domain package.
publish_to: none

environment:
  sdk: 3.2.6
  flutter: 3.16.9

dependencies:
  core_util:
    path: ../../../core/util

  freezed_annotation: 2.4.1
  json_annotation: 4.9.0

dev_dependencies:
  build_runner: 2.4.9
  freezed: 2.5.2
  json_serializable: 6.8.0
