name: my_domain
description: feature my domain package.
publish_to: none

environment:
  sdk: 3.3.4
  flutter: 3.19.6

dependencies:
  core_util:
    path: ../../../core/util

  freezed_annotation: 2.4.1
  json_annotation: 4.9.0

dev_dependencies:
  build_runner: 2.4.9
  freezed: 2.5.2
  json_serializable: 6.8.0
