name: core_util
description: core util package.
publish_to: none

environment:
  sdk: 3.3.4
  flutter: 3.19.6

dependencies:
  flutter:
    sdk: flutter

  custom_refresh_indicator: 3.1.0
  event_bus: 2.0.0
  firebase_core: 2.30.1
  firebase_remote_config: 4.4.4
  flutter_modular: 6.3.3
  flutter_svg: 2.0.10+1
  intl: 0.19.0
  shimmer: 3.0.0