name: tool_clind_network
description: tool clind network package.
publish_to: none

environment:
  sdk: 3.3.4
  flutter: 3.19.6

dependencies:
  flutter:
    sdk: flutter

  core_network:
    path: ../../../core/network