name: presentation
description: clind presentation package.
publish_to: none

environment:
  sdk: 3.3.4
  flutter: 3.19.6

dependencies:
  flutter:
    sdk: flutter

  domain:
    path: ../domain

  core_bloc:
    path: ../../core/bloc
  core_util:
    path: ../../core/util