name: community_presentation
description: feature community presentation package.
publish_to: none

environment:
  sdk: 3.3.4
  flutter: 3.19.6

dependencies:
  flutter:
    sdk: flutter

  community_domain:
    path: ../domain

  core_bloc:
    path: ../../../core/bloc
  core_util:
    path: ../../../core/util